In [1]:
# Q1
import numpy as np

arr1 = np.random.rand(5, 3)
arr2 = np.random.rand(3, 2)

dot = arr1.dot(arr2)

print(dot, dot.shape)

[[0.68773927 1.28485763]
 [0.49065682 0.7359927 ]
 [0.95569228 1.67813683]
 [0.15628373 0.25984452]
 [0.66952203 1.06538815]] (5, 2)


In [2]:
# Q2
import numpy as np

arr1 = np.array([[5, 7], [9, 11]], float) # 행렬 numpy
arr2 = np.array([[2, 4], [6, 8]], float)

concat_1 = np.concatenate((arr1, arr2), axis=0) # axis = 0, 행을 기준으로 
concat_2 = np.concatenate((arr1, arr2), axis=1) # axis = 1, 열을 기준으로

print(concat_1)
print(concat_2) # 출력

[[ 5.  7.]
 [ 9. 11.]
 [ 2.  4.]
 [ 6.  8.]]
[[ 5.  7.  2.  4.]
 [ 9. 11.  6.  8.]]


In [3]:
# Q3
import numpy as np

xy = np.array([[1., 2., 3., 4., 5., 6.,], [10., 20., 30., 40., 50., 60.,]])

x_train = xy[0,]
y_train = xy[1,] # 행과 열을 모두 가져올 때는 xy[행, 열]

print(x_train, x_train.shape)
print(y_train, y_train.shape)

[1. 2. 3. 4. 5. 6.] (6,)
[10. 20. 30. 40. 50. 60.] (6,)


In [4]:
# Q4
beta_gd = np.random.rand(1) 
bias = np.random.rand(1)

print(beta_gd, bias)

[0.51067452] [0.00839729]


In [6]:
# Q5
import numpy as np

xy = np.array([[1.,2.,3.,4.,5.,6.],
               [3.,6.,9.,12.,15.,18.]])

x_train=xy[0]
y_train=xy[1]

beta_gd=np.random.rand(1)
bias=np.random.rand(1)

learning_rate=0.001

for i in range(1000):
	pred=(x_train*beta_gd)+bias
	error=((pred-y_train)**2).mean()

	gd_w=((pred-y_train)*2*x_train).mean()
	gd_b=((pred-y_train)*2).mean()

	beta_gd -=learning_rate*gd_w
	bias -=learning_rate*gd_b

	if i % 100 == 0:
		print('Epoch({:10d}/1000)cost:{:10f},w:{:10f},b:{:10f}'.format(i,error,beta_gd.item(),bias.item()))

Epoch(         0/1000)cost:114.656004,w:  0.298522,b:  0.172737
Epoch(       100/1000)cost:  0.276523,w:  2.730418,b:  0.711969
Epoch(       200/1000)cost:  0.096925,w:  2.830706,b:  0.707618
Epoch(       300/1000)cost:  0.089861,w:  2.840292,b:  0.683077
Epoch(       400/1000)cost:  0.083534,w:  2.846153,b:  0.658625
Epoch(       500/1000)cost:  0.077653,w:  2.851672,b:  0.635019
Epoch(       600/1000)cost:  0.072186,w:  2.856989,b:  0.612259
Epoch(       700/1000)cost:  0.067104,w:  2.862115,b:  0.590313
Epoch(       800/1000)cost:  0.062380,w:  2.867057,b:  0.569155
Epoch(       900/1000)cost:  0.057988,w:  2.871822,b:  0.548755
